# Generated by Django 5.0 on 2025-05-02 07:09

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("prod_image", models.FileField(upload_to="Media/")),
                ("prod_desc", models.TextField()),
                ("prod_benefit", models.TextField()),
                ("prod_howtouse", models.TextField()),
                ("prod_imptips", models.TextField()),
                ("prod_Shinfo", models.TextField()),
                ("prod_nutinfo", models.TextField()),
            ],
        ),
    ]
