# Generated by Django 5.0 on 2025-05-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="prod_head",
            field=models.CharField(default="Default Head", max_length=50),
        ),
    ]
