# Generated by Django 5.0 on 2025-05-04 05:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "service",
            "0003_alter_product_prod_shinfo_alter_product_prod_benefit_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Enquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("subject", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("submitted_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
