# Generated by Django 5.0 on 2025-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("service", "0004_enquiry"),
    ]

    operations = [
        migrations.AddField(
            model_name="enquiry",
            name="company",
            field=models.CharField(default="Shriagro", max_length=50),
        ),
        migrations.AddField(
            model_name="enquiry",
            name="phone",
            field=models.IntegerField(default=123),
        ),
    ]
